### ISSUE TITLE
Why are there many copies in the dataset?

### ISSUE THREAD

**Issue by greecehalf** [preddy5/Im2Vec#14]

**Comment by greecehalf** [comment]
There are four copies for each sample in /data/emoji/ folder. I wonder the reasons for this. For augmentation? Thank you.

**Comment by preddy5** [comment]
Hey @greecehalf 
I am using an lr scheduler that decreases lr over epochs. Instead of changing the parameters of the scheduler for small datasets, I duplicated the images.
