### ISSUE TITLE
Segmentation tool

### ISSUE THREAD

**Issue by athenas-lab** [preddy5/Im2Vec#17]
Hi,

Could you please provide a link to the off-the-shelf segmentation tool (for "Depixelizing Pixel Art") that you have used for generating  your clustered samples,  so that we can cluster our dataset before using it to train im2vec? Will im2vec work without these clustered samples?

thanks

**Comment by preddy5** [comment]
Hey @athena913 
I didn't personally have to do it since I had access to SVG files of all the shapes I used. However, you can use something like this https://github.com/mehdidc/pixel_to_svg to generate the clusters. The repo contains code for a segmentation algorithm that you can use for preprocessing. 

Regards,

**Comment by athenas-lab** [comment]
Hi,
Based on the paper, my understanding was that im2vec can work on image datasets that do not  have a vector counterpart. But based on your response it seems like during preprocessing we either need the SVG counterpart or use an algorithm to perform segmentation/clustering. I looked though your codebase but could not find the segmentation code or preprocessing code you are referring to (in experiment.py, there is a train_dataloader() but it does some standard image transformations on the already preprocessed dataset).  

I am interested in training/evaluating im2vec on 2 public icon datasets for reconstruction as well as generating variations.  One of the datasets has both the image and svg files, while the other has only the image files. Some of these icons are colored while the others are just black and white.
1) Could you please provide some guidance on the preprocessing steps involved for the dataset that has only the image files? 

2) Also, could you please provide some guidance on the preprocessing steps involved for the dataset that has both the image and svg counterpart? 

Alternatively, if  you already have the preprocessing code for each case,  is it possible to share that?

Thanks for your help.

**Comment by preddy5** [comment]
Hey,
Yes, you are right we do not need the vector counterparts for im2vec however the input images need to be preprocessed to get the best results. Yes, you are also right that the codebase doesn't contain any preprocessing code. 
In my case I used this bit of code to generate colored images of the font https://gist.github.com/preddy5/c626189cbf548d915d0079b9a40cdb08 this code takes ttf(this is often how font are stored) files as the input and saves a colored png file, you could do something similar with SVG files. 
For icons and emojis examples shown in the paper, I colored some of them manually using photoshop. Depending on the size of your dataset you could maybe try doing it manually or automate it using segmentation algorithms either like the one, I mentioned earlier or opensource implementations like this one https://github.com/vvanirudh/Pixel-Art/tree/e929ef1bdd9b1c46f063f309a3309bd362e51097 

Hope that helps

**Comment by athenas-lab** [comment]
Hi,
For font datasets, some recent methods like DeepVecFont generate the drawing commands from images/ttf, which are then used for reconstruction and variations.   For a large dataset of generic icons with complex topologies, I am not sure how feasible it is to automate the clustering process based on colors, but thanks for the links, I will check it out.
