### ISSUE TITLE
Speeding up training and using attention

### ISSUE THREAD

**Issue by IzhanVarsky** [preddy5/Im2Vec#18]
Hi, nice work! Have you tried using RNN with attention? And is it possible to generate large shapes from the very beginning, not small dots?

**Comment by preddy5** [comment]
Hey @IzhanVarsky 
i) no I haven't experimented with attention-based networks in the context of this project. 
ii) To the best of my knowledge that wouldn't be possible without coming up with a different NN weight initialization scheme. 
    A simpler solution would be to pre-train the network to estimate large shapes first and then train on the dataset of choice, however, I haven't tested this.
