### ISSUE TITLE
ModuleNotFoundError: No module named 'pydiffvg'

### ISSUE THREAD

**Issue by DYF-AI** [preddy5/Im2Vec#2]
This is an interesting project，How to install pydiffvg？
import pydiffvg
ModuleNotFoundError: No module named 'pydiffvg'

```shell
python3 -m pip install diffvg
ERROR: Could not find a version that satisfies the requirement diffvg
ERROR: No matching distribution found for diffvg

```shell
python3 -m pip install pydiffvg
ERROR: Could not find a version that satisfies the requirement pydiffvg
ERROR: No matching distribution found for pydiffvg

**Comment by preddy5** [comment]
Hey @DYF-AI you can find diffvg here https://github.com/BachiLi/diffvg

**Comment by DYF-AI** [comment]
Thanks●‿● Yongfei Dong ***@***.*** 签名由 网易邮箱大师 定制 On 04/15/2021 21:57, Pradyumna Reddy Chinthala wrote: Hey @DYF-AI you can find diffvg here https://github.com/BachiLi/diffvg — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
