### ISSUE TITLE
How to train with celeba dataset?

### ISSUE THREAD

**Issue by TLi347** [preddy5/Im2Vec#9]
Hi,

I noticed that there is a celeba dataset train interface in dataloader. How do we train with this dataset? Do I need to change the self.colors in VectorVAEnLayers class?

Thank you.

**Comment by preddy5** [comment]
Hey @TLi347 it is a remnant of few old experiments. Sorry no, we cannot on celeba dataset.

**Comment by TLi347** [comment]
Hi @preddy5 

Thank you for such a quick response. I have to ask one more question. Have you test on celeba dataset?
